### ISSUE TITLE
sourceUriPath does not allow urlencoded special chars

### ISSUE THREAD

**Issue by dezio** [neos/redirecthandler-ui#72]
Hello,

we created a new site for someone and have been using the redirect Ui for redirecting old links.

Now to the problem
The sourceUriPath pattern  '^[a-zA-Z0-9_\-\/\.]+$' does not allow:

- getränkekarte.pdf
- getr%C3%A4nkekarte.pdf

I've changed the pattern in my Configuration/Settings.yaml to `^[a-zA-Z0-9_\-\/\.\%]+$`, but this didn't work, as the backend keeps telling me its not matching the (old) pattern.

Is there a problem with neos handling those urls or would it be safe to allow the % char?

Until then, we'll stick to the good old htaccess-RewriteRules.

Greetings and thanks!

**Comment by Sebobo** [comment]
Did you change both configurations. The one for the redirect handler and the one for the ui?
Sadly there are two regex configs as the regex for the UI validation has to be written differently.

Then it should work.

You have to test if it works with `%`. I added the regex that Neos itself uses for nodeuri validation as default and because uris are complicated made it configurable.

But probably there could be a better default probably.

**Comment by Sebobo** [comment]
Related fixes https://github.com/neos/redirecthandler-ui/commit/0bfaed63d350bc63dd417cbb7beb248803f16f61 and  https://github.com/neos/redirecthandler/commit/dea25ff8e1cbd2f301e7873cadd19fcaac879a4a

**Comment by Sebobo** [comment]
Just released new versions of redirecthandler and the ui to adjust the default validation setting in PHP and in JS
